language: node_js
node_js: 10

before_script:
  - npm install -g @angular/cli
  - npm install -g codecov

script:
  - ng lint
  #- ng test
  - ng build --prod

after_success:
  - codecov
  # - yarn packagr
  # - yarn publish

notifications:
  email:
    on_failure: change
    on_success: change