language: node_js
node_js: 10

before_script:
  - npm install -g @angular/cli
  - ng lint

script:
  - npm install codecov -g
  - ng build --prod

after_success:
  - codecov
  # - yarn packagr
  # - yarn publish

notifications:
  email:
    false
    # on_failure: change
    # on_success: change