language: node_js
node_js: 10

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install -g codecov

script:
  - ng lint
  - node_modules/karma/bin/karma start test/karma.conf.js --single-run
  #- ng test
  - ng build --prod

after_success:
  - codecov
  # - yarn packagr
  # - yarn publish

notifications:
  email:
    on_failure: change
    on_success: change